### ISSUE TITLE
SqlClient is slow on Linux

### ISSUE THREAD

**Issue by sebastienros** [aspnet/DataAccessPerformance#26]
Performance results running https://github.com/aspnet/benchmarks/tree/dev/src/Benchmarks with Sql Server. The results matrix show the results of comparing NodeJs on Linux, Undertow on Linux, .NET Core on Linux and .NET Core on Windows.

- __This is a load test, not a raw access performance__, which is aimed at showing concurrency issues and bottleneck. So even if the client can be seen as fast, this test shows different behavior under load.
- The tests are done with the same SQL Server instance running in a Linux Docker image.
- The Cloud machines are Azure D3v2 VMs. 
- The database is always on the same private network as the servers.
- The results are expressed in Requests by Second.
- This has been tested withthe runtime version `2.1.0-preview2-26130-04`

Platform | Cloud | Physical
-- | -- | --
NodeJs | 7,157 | 22,704
Undertow (Java)  | 9,075 | 40,365
.NET Core on Linux | 1,294 | 7,481
.NET Core on Windows | 14,118 | 69,000

/cc @geleems @saurabh500

**Comment by saurabh500** [comment]
@sebastienros Will it be safe to assume that on physical SQL server the protocol enabled was only TCP and not Shared Memory or Named Pipe ?

**Comment by saurabh500** [comment]
The reason I ask is because I have seen dramatic difference in performance while using Shared Memory over TCP while communicating with physical SQL server on Windows. The SQL server and client on Linux only supports TCP.

**Comment by saurabh500** [comment]
@sebastienros  what was the driver used with Undertow? Was it MSSQL-JDBC?

**Comment by saurabh500** [comment]
@sebastienros I haven't been able to setup the ASP.Net Tech empower benchmarks. However I have been running the DataAccessPerformance repo's benchmarks. 

I have upgraded the SqlClient package to 4.5.0-preview2-26202-05 from myget, which contains the performance fixes that we had targetted. 

I see on Ubuntu 1604, the tps increase from 3100 tps to 4800 tps for sync
At the same time, I have seen the async performance improve from an extremely low < 100 tps to ~600 tps on the same ubuntu machine, connecting to Physical Sql Server (on premise on Microsoft network) 

Is it a requirement to run these benchmarks against 4.4.0 of SqlClient? SqlClient moved out of the 2.0 runtime and is no more a part of the Core runtime. Hence the version of SqlClient needs to be updated manually.

**Comment by sebastienros** [comment]
> the version of SqlClient needs to be updated manually

That might explain, I will look into this

**Comment by sebastienros** [comment]
Undertow is using the JDBC driver
NodeJS is using Tedious 1.7.0

**Comment by sebastienros** [comment]
The server is running in Linux, so it can only be TCP, for both the Windows and Linux clients, in all tests I ran.

**Comment by saurabh500** [comment]
@sebastienros Thanks for the replies. It will be good to see the results with new SqlClient. Good to know that the constant protocol assumption was true.
 
For the techempower benchmarks, I see that it is dependent on EF Core and has no direct reference to SqlClient. EF core is on a Dec 12 2017 build of SqlClient as well. So it may be good to get numbers from the lab with an updated SqlClient in EF.

**Comment by sebastienros** [comment]
I have a tool to dump all the assemblies that are used during the runs, and here is the one it's actually using from the windows machine:

`C:\Users\Administrator\AppData\Local\Temp\2\tmpB944.tmp\jbnoxvsc.bj4\benchmarks\src\Benchmarks\published\runtimes\win\lib\netstandard2.0\System.Data.SqlClient.dll System.Data.SqlClient.dll 4.3.1.0 4.6.26130.01 @BuiltBy: dlab-DDVSOWINAGE053 @SrcCode: https://github.com/dotnet/corefx/tree/5b5eacfce3a62712ceb67dfb51128221b0fce137`

And the commit id here is very recent.

But I found an issue with the linux environment that might be the cause of the linux results, I will update this issue once I have more information.

**Comment by sebastienros** [comment]
On linux I was using `4.5.0-preview2-26130-01`, can you tell me from that number if it had the fix?

**Comment by saurabh500** [comment]
This is a slightly old package which doesn't have some fixes for async SqlDataReader. I recommend 4.5.0-preview2-26202-05

**Comment by sebastienros** [comment]
Checked with a new package that was provided and it's fixed.
